### ISSUE TITLE
getent Utility Missing?

### ISSUE THREAD

**Issue by veritas06** [Sadi58/hostsblock#12]
Seem to be having a problem with the install:

```
v3ritas@ubuntu-y70:~/Development/hostsblock$ sudo !!

sudo ./install.sh 

getent utility missing. Please install before running this script. Exiting...

v3ritas@ubuntu-y70:~/Development/hostsblock$ getent --version

getent (Ubuntu GLIBC 2.24-9ubuntu2.2) 2.24

Copyright (C) 2016 Free Software Foundation, Inc.

This is free software; see the source for copying conditions.  There is NO

warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Written by Thorsten Kukuk.
```

**Comment by Sadi58** [comment]
Can you please **re-open** this issue at the relevant upstream location?
https://github.com/gaenserich/hostsblock/issues

I'm only responsible for the files in **./indicator** subdirectory aimed at merely providing a GUI interface for **hostsblock** and I haven't updated the indicator version after the recent upstream changes to see if it is stable enough.
