### ISSUE TITLE
Add the CoinBlockerLists

### ISSUE THREAD

**Issue by ZeroDot1** [Sadi58/hostsblock#14]
Hi, I'm the creator of the CoinBlockerLists, is it possible to add the CoinBlockerLists to your project?
https://github.com/ZeroDot1/CoinBlockerLists
CoinBlockerLists Short URL: [https://git.io/vFFKT](https://git.io/vFFKT)

| Format | Description | URL |
| --- | --- | --- |
| List | This list contains all domains - A list for administrators to prevent mining in networks| [RAW = list.txt](https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list.txt) |
| List | This list contains all optional domains - An additional list for administrators| [RAW = list_optional.txt](https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_optional.txt) |
| List | This list contains all browser mining domains - A list to prevent browser mining only| [RAW = list_browser.txt](https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_browser.txt) |
| Hosts | This list contains all domains - A hostslist for administrators to prevent mining in networks| [RAW = hosts](https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/hosts) |
| Hosts | This list contains all optional domains - An additional hostslist for administrators| [RAW = hosts_optional](https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/hosts_optional) |
| Hosts | This list contains all browser mining domains - A hostslist to prevent browser mining only| [RAW = hosts_browser](https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/hosts_browser) |
| List | This list contains all IPs - A additional list for administrators to prevent mining in networks| [RAW = MiningServerIPList.txt](https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/MiningServerIPList.txt) |

**Comment by Sadi58** [comment]
Hi, and thanks...
But can you make this request here please: https://github.com/gaenserich/hostsblock/issues/new
As I've just done the indicator (GUI) part here, and the real thing is there, which is used by many more people...

**Comment by ZeroDot1** [comment]
Yes, thank you for the tip.
